name: gh-release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: printenv
        run: printenv
      - name: Install dependencies
        run: brew install scdoc
      - name: Install ARM target
        run: rustup update && rustup target add aarch64-apple-darwin && rustup target add x86_64-apple-darwin
      - name: Test
        run: cargo test --release --target=x86_64-apple-darwin
      - name: Build ARM
        run: cargo build --release --target=aarch64-apple-darwin
      - name: Make DMG
        run: make dmg-universal
      - name: Upload Application
        run: |
          mv ./target/release/osx/gnostr.dmg ./gnostr-${GITHUB_REF##*/}.dmg
          ./.github/workflows/upload_asset.sh ./gnostr-${GITHUB_REF##*/}.dmg $GH_TOKEN

  windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: cargo test --release
      - name: Build
        run: cargo build --release
      - name: Upload portable executable
        run: |
          cp ./target/release/alacritty.exe ./Alacritty-${GITHUB_REF##*/}-portable.exe
          ./.github/workflows/upload_asset.sh \
            ./Alacritty-${GITHUB_REF##*/}-portable.exe $GH_TOKEN
      - name: Install WiX
        run: dotnet tool install --global wix --version 4.0.5
      - name: Create msi installer
        run: |
          wix extension add WixToolset.UI.wixext/4.0.5 WixToolset.Util.wixext/4.0.5
          wix build -arch "x64" -ext WixToolset.UI.wixext -ext WixToolset.Util.wixext \
          -out "./Alacritty-${GITHUB_REF##*/}-installer.msi" "alacritty/windows/wix/alacritty.wxs"
      - name: Upload msi installer
        run: |
          ./.github/workflows/upload_asset.sh \
            ./Alacritty-${GITHUB_REF##*/}-installer.msi $GH_TOKEN

  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get install cmake pkg-config libfreetype6-dev libfontconfig1-dev \
            libxcb-xfixes0-dev libxkbcommon-dev python3 scdoc
      - name: Test
        run: cargo test --release
      - name: Generate manpages
        run: |
          scdoc < extra/man/alacritty.1.scd | gzip -c > "./alacritty.1.gz"
          scdoc < extra/man/alacritty-msg.1.scd | gzip -c > "./alacritty-msg.1.gz"
          scdoc < extra/man/alacritty.5.scd | gzip -c > "./alacritty.5.gz"
          scdoc < extra/man/alacritty-bindings.5.scd | gzip -c > "./alacritty-bindings.5.gz"
      - name: Upload Assets
        run: |
          #mv ./extra/logo/alacritty-term.svg ./Alacritty.svg
          #./.github/workflows/upload_asset.sh ./Alacritty.svg $GH_TOKEN
          #./.github/workflows/upload_asset.sh ./alacritty.1.gz $GH_TOKEN
          #./.github/workflows/upload_asset.sh ./alacritty-msg.1.gz $GH_TOKEN
          #./.github/workflows/upload_asset.sh ./alacritty.5.gz $GH_TOKEN
          #./.github/workflows/upload_asset.sh ./alacritty-bindings.5.gz $GH_TOKEN
          #./.github/workflows/upload_asset.sh ./extra/completions/alacritty.bash $GH_TOKEN
          #./.github/workflows/upload_asset.sh ./extra/completions/alacritty.fish $GH_TOKEN
          #./.github/workflows/upload_asset.sh ./extra/completions/_alacritty $GH_TOKEN
          #./.github/workflows/upload_asset.sh ./extra/linux/Alacritty.desktop $GH_TOKEN
          #./.github/workflows/upload_asset.sh ./extra/alacritty.info $GH_TOKEN
